# Generated by Django 4.1.5 on 2023-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sdet', models.CharField(max_length=70)),
                ('detail', models.CharField(max_length=500)),
                ('cat', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
