# Generated by Django 4.1.5 on 2023-02-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 2, 13, 10, 32, 54, 752854, tzinfo=datetime.timezone.utc)),
        ),
    ]
